sudo: required

language: python
python:
    - "2.7"

notifications:
    email:
        on_success: never
        on_failure: never

before_install:
  - pip install codecov

after_success:
  - codecov

install: "pip install -r requirements.txt"
script:
    - nosetests --with-cov
